---
- name: Remove managedCluster resource: {{ cluster.name }}
  kubernetes.core.k8s:
    state: absent
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    wait: false
  when: destroy

- name: Destroy cluster: {{ cluster.name }}
  kubernetes.core.k8s:
    state: absent
    api_version: hive.openshift.io/v1
    kind: ClusterDeployment
    name: "{{ cluster.name }}"
    namespace: "{{ cluster.namespace | default('hive') }}"
    wait: false
  register: destroy_cluster
  when: destroy

- name: Wait for ClusterDeployment to be fully deleted: {{ cluster.name }}
  kubernetes.core.k8s_info:
    api_version: hive.openshift.io/v1
    kind: ClusterDeployment
    name: "{{ cluster.name }}"
    namespace: "{{ cluster.namespace | default('hive') }}"
  register: deletion_status
  until:
    - deletion_status.resources is not defined or deletion_status.resources | length == 0
  retries: 120
  delay: 10
  when: destroy

- name: Remove directory: {{ deployment_config_dir }}
  ansible.builtin.file:
    state: absent
    path: "{{ deployment_config_dir }}"
  when:
    - destroy
    - deletion_status is succeeded
