apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus.name" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nexus.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nexus.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers.enabled }}
      initContainers:
      {{- with .Values.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command: [ "/bin/sh","-c" ]
          args: [ "chown -R 200:200 /nexus-data" ]
      {{- with $.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
      {{- end }}
          resources:
            requests:
              cpu: "{{ .requests.cpu }}"
              memory: "{{ .requests.memory }}"
            limits:
              cpu: "{{ .limits.cpu }}"
              memory: "{{ .limits.memory }}"
          volumeMounts:
            - name: data-vol
              mountPath: /nexus-data
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          {{- range .Values.env }}
            - name:  {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - name: {{ .Values.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ include "nexus.name" . }}-pv
